#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in2,    power,          sensorAnalog)
#pragma config(Sensor, in3,    gyro,         sensorGyro)
#pragma config(Sensor, in4,    Catapult_Pot,   sensorPotentiometer)
#pragma config(Sensor, dgtl1,  SONAR_F,        sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  SONAR_B,        sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  Encod_R,        sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  Encod_L,        sensorQuadEncoder)
#pragma config(Motor,  port1,           Chasis_R1,     tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port2,           Ball_Intake_1, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Chasis_R2,     tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port4,           Chasis_R3,     tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port5,           Catapult_1,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Catapult_2,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Chasis_L3,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl7)
#pragma config(Motor,  port8,           Chasis_L2,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl7)
#pragma config(Motor,  port9,           Ball_Intake_2, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Chasis_L1,     tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft, encoderPort, dgtl7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "library/pid_h.h"
#include "library/simplifications and variables.h"

int gyroTolerance = 0;

//function for the right chassis
void right_chassis(int speed){
	motor[Chasis_R1]=speed;
	motor[Chasis_R2]=speed;
	motor[Chasis_R3]=speed;
}
//function for the left chassis
void left_chassis(int speed){
	motor[Chasis_L1]=speed;
	motor[Chasis_L2]=speed;
	motor[Chasis_L3]=speed;
}

//function to calibrate gyro
void dgyro_chassis_init(){
	D_gyro = sensorNone;
	wait1Msec(200);
	D_gyro = sensorGyro;
	wait1Msec(100);
}

void _drivegyro(float angle, int speed){
	dgyro_chassis_init();
	//angle = ((345/120)*speed)+angle);
	angle = angle+159

	if((D_gyro) < angle - 100){
		int gyroError = abs(angle)-abs(D_gyro);
		while((D_gyro) < angle - 100){
			//...Continue turning
			right_chassis(-speed);
			left_chassis(speed);
			gyroError = abs(angle)-abs(D_gyro);
		}
		//Brief brake to eliminate some drift
		right_chassis(25);
		left_chassis(-25);
		wait1Msec(100);
		//Second while loop to move more slowly toward the goal
		while((D_gyro) != angle && abs(gyroError) > gyroTolerance){
			if((D_gyro) > angle){
				right_chassis(40);
				left_chassis(-40);
				}else{
				right_chassis(-40);
				left_chassis(40);
			}
			gyroError = abs(angle)-abs(D_gyro);
		}
		//Stop
		right_chassis(0);
		left_chassis(0);
		wait1Msec(100);
		}else{
		int gyroError = abs(angle)-abs(D_gyro);
		while((D_gyro) > angle - 100){
			//...Continue turning
			right_chassis(speed);
			left_chassis(-speed);
			gyroError = abs(angle)-abs(D_gyro);
		}
		//Brief brake to eliminate some drift
		right_chassis(-25);
		left_chassis(25);
		wait1Msec(100);
		//Second while loop to move more slowly toward the goal
		while((D_gyro) != angle && abs(gyroError) > gyroTolerance){
			if((D_gyro) < angle){
				right_chassis(-40);
				left_chassis(40);
				}else{
				right_chassis(40);
				left_chassis(-40);
			}
			gyroError = abs(angle)-abs(D_gyro);
		}
		//Stop
		right_chassis(0);
		left_chassis(0);
		wait1Msec(100);
	}
}

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
}
task usercontrol()
{
}

task autonomous()
{
	_drivegyro(900, 120);
}
