#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool brake(){

}

task main(){
	while(true){

/*	if (vexRT[Btn6U] == 1)
	{
		int speed = vexRT[Ch1];
		motor[motor1] = -speed;
		motor[motor2] = speed;
		motor[motor3] = speed;
		motor[motor4] = -speed;
 }
 else if (vexRT[Btn5U] == 1){
   int speed = vexRT[Ch1];
   motor[motor1] = speed;
	 motor[motor2] = -speed;
	 motor[motor3] = -speed;
	 motor[motor4] = speed;
 }
 else{
   motor[motor1] = vexRT[Ch2] - vexRT[Ch1];
   motor[motor2] = vexRT[Ch2] - vexRT[Ch1];
   motor[motor3] = vexRT[Ch2] + vexRT[Ch1];
   motor[motor4] = vexRT[Ch2] + vexRT[Ch1];
}*/

motor[motor1] = vexRT[Ch3];
motor[motor2] = vexRT[Ch3];
motor[motor3] = vexRT[Ch3];
motor[motor4] = vexRT[Ch3];
}
}
