#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    Catapult_Pot,   sensorPotentiometer)
#pragma config(Sensor, in2,    power,          sensorAnalog)
#pragma config(Motor,  port1,           Chasis_L1,     tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port2,           Chasis_L2,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port3,           Chasis_L3,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Ball_Intake,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Catapult_1,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Catapult_2,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           Descorer,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Chasis_R3,     tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           Chasis_R2,     tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          Chasis_R1,     tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


// Sensor(s) detected, nice!
// Integeated Encoder Module(s) detected, sweet!
// Begin recording in:  3 . . . . 2 . . . . 1 . . . .
// BEGIN AUTONOMOUS RECORDING
/*<<<<---- START COPY ----------------------------------------------------------------------*/
int R_Freq = 50;
int R_Batt = 8569;
int P_Freq = R_Freq * (R_Batt / nImmediateBatteryLevel)
// Initial values for Sensors: in 1 = 857  in 2 = 2393
// Initial values for IMEs: port 1 = 0  port 2 = 0  port 3 = 0
wait1Msec( P_Freq * 1 );		// wait 50

// 50  Sensors: in 2 = 2228  IMEs: no change
motor[ port4 ] = 127;
wait1Msec( P_Freq * 13 );		// wait 650

// 700  Sensors: in 2 = 2298  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 12 );		// wait 600

// 1300  Sensors: in 2 = 2314  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 33 );		// wait 1650

// 2950  Sensors: in 2 = 2242  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 10 );		// wait 500

// 3450  Sensors: in 2 = 2292  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 14 );		// wait 700

// 4150  Sensors: in 2 = 2343  IMEs: no change
motor[ port4 ] = 0;
wait1Msec( P_Freq * 13 );		// wait 650

// 4800  Sensors: in 2 = 2380  IMEs: no change
motor[ port1 ] = 9;
motor[ port2 ] = 9;
motor[ port3 ] = 9;
motor[ port8 ] = -20;
motor[ port9 ] = -20;
motor[ port10 ] = -20;
wait1Msec( P_Freq * 1 );		// wait 50

// 4850  Sensors: no change  IMEs: no change
motor[ port1 ] = 21;
motor[ port2 ] = 21;
motor[ port3 ] = 21;
motor[ port8 ] = -32;
motor[ port9 ] = -32;
motor[ port10 ] = -32;
wait1Msec( P_Freq * 1 );		// wait 50

// 4900  Sensors: no change  IMEs: no change
motor[ port1 ] = 35;
motor[ port2 ] = 35;
motor[ port3 ] = 35;
motor[ port8 ] = -42;
motor[ port9 ] = -42;
motor[ port10 ] = -42;
wait1Msec( P_Freq * 3 );		// wait 150

// 5050  Sensors: no change  IMEs: no change
motor[ port1 ] = 38;
motor[ port2 ] = 38;
motor[ port3 ] = 38;
wait1Msec( P_Freq * 12 );		// wait 600

// 5650  Sensors: no change  IMEs: no change
motor[ port1 ] = 33;
motor[ port2 ] = 33;
motor[ port3 ] = 33;
motor[ port8 ] = -7;
motor[ port9 ] = -7;
motor[ port10 ] = -7;
wait1Msec( P_Freq * 2 );		// wait 100

// 5750  Sensors: in 2 = 2383  IMEs: no change
motor[ port1 ] = 8;
motor[ port2 ] = 8;
motor[ port3 ] = 8;
wait1Msec( P_Freq * 3 );		// wait 150

// 5900  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 3 );		// wait 150

// 6050  Sensors: no change  IMEs: no change
motor[ port1 ] = -5;
motor[ port2 ] = -5;
motor[ port3 ] = -5;
wait1Msec( P_Freq * 1 );		// wait 50

// 6100  Sensors: no change  IMEs: no change
motor[ port1 ] = -24;
motor[ port2 ] = -24;
motor[ port3 ] = -24;
wait1Msec( P_Freq * 1 );		// wait 50

// 6150  Sensors: no change  IMEs: no change
motor[ port1 ] = -83;
motor[ port2 ] = -83;
motor[ port3 ] = -83;
motor[ port8 ] = 28;
motor[ port9 ] = 28;
motor[ port10 ] = 28;
wait1Msec( P_Freq * 1 );		// wait 50

// 6200  Sensors: no change  IMEs: no change
motor[ port1 ] = 42;
motor[ port2 ] = 42;
motor[ port3 ] = 42;
motor[ port8 ] = 34;
motor[ port9 ] = 34;
motor[ port10 ] = 34;
wait1Msec( P_Freq * 1 );		// wait 50

// 6250  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 4 );		// wait 200

// 6450  Sensors: no change  IMEs: no change
motor[ port1 ] = 40;
motor[ port2 ] = 40;
motor[ port3 ] = 40;
motor[ port8 ] = 40;
motor[ port9 ] = 40;
motor[ port10 ] = 40;
wait1Msec( P_Freq * 2 );		// wait 100

// 6550  Sensors: no change  IMEs: no change
motor[ port1 ] = 108;
motor[ port2 ] = 108;
motor[ port3 ] = 108;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 10 );		// wait 500

// 7050  Sensors: no change  IMEs: no change
motor[ port1 ] = 104;
motor[ port2 ] = 104;
motor[ port3 ] = 104;
wait1Msec( P_Freq * 6 );		// wait 300

// 7350  Sensors: in 1 = 854  IMEs: no change
motor[ port1 ] = 81;
motor[ port2 ] = 81;
motor[ port3 ] = -16;
motor[ port8 ] = -5;
motor[ port9 ] = -5;
motor[ port10 ] = -5;
wait1Msec( P_Freq * 1 );		// wait 50

// 7400  Sensors: in 1 = 858  IMEs: no change
motor[ port1 ] = -16;
motor[ port2 ] = -16;
wait1Msec( P_Freq * 1 );		// wait 50

// 7450  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 19 );		// wait 950

// 8400  Sensors: no change  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 67 );		// wait 3350

// 11750  Sensors: in 2 = 2386  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 12 );		// wait 600

// 12350  Sensors: no change  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 15 );		// wait 750

// 13100  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 7 );		// wait 350

// 13450  Sensors: in 1 = 851  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 1 );		// wait 50

// 13500  Sensors: in 1 = 856  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 17 );		// wait 850

// 14350  Sensors: no change  IMEs: no change
motor[ port5 ] = 127;
motor[ port6 ] = 127;
wait1Msec( P_Freq * 23 );		// wait 1150

// 15500  Sensors: in 1 = 727  in 2 = 2246  IMEs: no change
motor[ port5 ] = 0;
motor[ port6 ] = 0;

}
