#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    Catapult_Pot,   sensorPotentiometer)
#pragma config(Sensor, in2,    power,          sensorAnalog)
#pragma config(Motor,  port1,           Chasis_L1,     tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port2,           Chasis_L2,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port3,           Chasis_L3,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Ball_Intake,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Catapult_1,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Catapult_2,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           Descorer,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Chasis_R3,     tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           Chasis_R2,     tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          Chasis_R1,     tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

{



// Sensor(s) detected, nice!
// Integeated Encoder Module(s) detected, sweet!
// Begin recording in:  3 . . . . 2 . . . . 1 . . . .
// BEGIN AUTONOMOUS RECORDING
/*<<<<---- START COPY ----------------------------------------------------------------------*/
int R_Freq = 50;
int R_Batt = 8628;
int P_Freq = R_Freq * (R_Batt / nImmediateBatteryLevel)
// Initial values for Sensors: in 1 = 854  in 2 = 2288
// Initial values for IMEs: port 1 = 0  port 2 = 0  port 3 = 0

// 50  Sensors: no change  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 24 );		// wait 1200

// 1250  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 17 );		// wait 850

// 2100  Sensors: no change  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 7 );		// wait 350

// 2450  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 7 );		// wait 350

// 2800  Sensors: no change  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 3 );		// wait 150

// 2950  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 21 );		// wait 1050

// 4000  Sensors: no change  IMEs: no change
motor[ port5 ] = 127;
motor[ port6 ] = 127;
wait1Msec( P_Freq * 24 );		// wait 1200

// 5200  Sensors: in 1 = 738  in 2 = 2248  IMEs: no change
motor[ port5 ] = 0;
motor[ port6 ] = 0;
wait1Msec( P_Freq * 1 );		// wait 50

// 5250  Sensors: in 1 = 735  in 2 = 2386  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 8 );		// wait 400

// 5650  Sensors: in 2 = 2397  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 17 );		// wait 850

// 6500  Sensors: no change  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 1 );		// wait 50

// 650  Sensors: no change  IMEs: no change
motor[ port1 ] = -13;
motor[ port2 ] = -13;
motor[ port3 ] = -13;
motor[ port8 ] = 11;
motor[ port9 ] = 11;
motor[ port10 ] = 11;
wait1Msec( P_Freq * 1 );		// wait 50

// 700  Sensors: no change  IMEs: no change
motor[ port1 ] = -19;
motor[ port2 ] = -19;
motor[ port3 ] = -19;
motor[ port8 ] = 15;
motor[ port9 ] = 15;
motor[ port10 ] = 15;
wait1Msec( P_Freq * 1 );		// wait 50

// 750  Sensors: no change  IMEs: no change
motor[ port1 ] = -42;
motor[ port2 ] = -42;
motor[ port3 ] = -42;
motor[ port8 ] = 51;
motor[ port9 ] = 51;
motor[ port10 ] = 51;
wait1Msec( P_Freq * 1 );		// wait 50

// 800  Sensors: no change  IMEs: no change
motor[ port8 ] = 77;
motor[ port9 ] = 77;
motor[ port10 ] = 77;
wait1Msec( P_Freq * 2 );		// wait 100

// 900  Sensors: no change  IMEs: no change
motor[ port8 ] = 82;
motor[ port9 ] = 82;
motor[ port10 ] = 82;
wait1Msec( P_Freq * 4 );		// wait 200

// 1100  Sensors: no change  IMEs: no change
motor[ port1 ] = -19;
motor[ port2 ] = -19;
motor[ port3 ] = -19;
motor[ port8 ] = 52;
motor[ port9 ] = 52;
motor[ port10 ] = 52;
wait1Msec( P_Freq * 1 );		// wait 50

// 1150  Sensors: no change  IMEs: no change
motor[ port1 ] = -14;
motor[ port2 ] = -14;
motor[ port3 ] = -14;
wait1Msec( P_Freq * 2 );		// wait 100

// 1250  Sensors: no change  IMEs: no change
motor[ port8 ] = 48;
motor[ port9 ] = 48;
motor[ port10 ] = 48;
wait1Msec( P_Freq * 1 );		// wait 50

// 1300  Sensors: no change  IMEs: no change
motor[ port1 ] = -5;
motor[ port2 ] = -5;
motor[ port3 ] = -5;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 13 );		// wait 650

// 1950  Sensors: no change  IMEs: no change
motor[ port1 ] = -43;
motor[ port2 ] = -43;
motor[ port3 ] = -43;
motor[ port8 ] = -25;
motor[ port9 ] = -25;
motor[ port10 ] = -25;
wait1Msec( P_Freq * 1 );		// wait 50

// 2000  Sensors: no change  IMEs: no change
motor[ port1 ] = -59;
motor[ port2 ] = -59;
motor[ port3 ] = -59;
motor[ port8 ] = -46;
motor[ port9 ] = -46;
motor[ port10 ] = -46;
wait1Msec( P_Freq * 1 );		// wait 50

// 2050  Sensors: no change  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 5 );		// wait 250

// 2300  Sensors: no change  IMEs: no change
motor[ port1 ] = 43;
motor[ port2 ] = 43;
motor[ port3 ] = 43;
motor[ port8 ] = -80;
motor[ port9 ] = -80;
motor[ port10 ] = -80;
wait1Msec( P_Freq * 1 );		// wait 50

// 2350  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;

// 50  Sensors: in 2 = 2221  IMEs: no change
motor[ port4 ] = 127;
wait1Msec( P_Freq * 11 );		// wait 550

// 600  Sensors: in 2 = 2335  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 17 );		// wait 850

// 1450  Sensors: in 2 = 2320  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 21 );		// wait 1050

// 2500  Sensors: in 2 = 2191  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 2 );		// wait 100

// 2600  Sensors: in 2 = 2135  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 10 );		// wait 500

// 3100  Sensors: in 2 = 2304  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 2 );		// wait 100

// 3200  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 11 );		// wait 550

// Sensor(s) detected, nice!
// Integeated Encoder Module(s) detected, sweet!
// Begin recording in:  3 . . . . 2 . . . . 1 . . . .
// BEGIN AUTONOMOUS RECORDING
/*<<<<---- START COPY ----------------------------------------------------------------------*/

// 750  Sensors: in 1 = 862  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 4 );		// wait 200

// 950  Sensors: in 1 = 866  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 6 );		// wait 300

// 1250  Sensors: no change  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 3 );		// wait 150

// 1400  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 12 );		// wait 600

// 2000  Sensors: no change  IMEs: no change
motor[ port8 ] = -5;
motor[ port9 ] = -5;
motor[ port10 ] = -5;
wait1Msec( P_Freq * 2 );		// wait 100

// 2100  Sensors: no change  IMEs: no change
motor[ port1 ] = -6;
motor[ port2 ] = -6;
motor[ port3 ] = -6;
motor[ port8 ] = -20;
motor[ port9 ] = -20;
motor[ port10 ] = -20;
wait1Msec( P_Freq * 1 );		// wait 50

// 2150  Sensors: no change  IMEs: no change
motor[ port8 ] = -31;
motor[ port9 ] = -31;
motor[ port10 ] = -31;
wait1Msec( P_Freq * 4 );		// wait 200

// 2350  Sensors: no change  IMEs: no change
motor[ port8 ] = -27;
motor[ port9 ] = -27;
motor[ port10 ] = -27;
wait1Msec( P_Freq * 1 );		// wait 50

// 2400  Sensors: no change  IMEs: no change
motor[ port8 ] = -24;
motor[ port9 ] = -24;
motor[ port10 ] = -24;
wait1Msec( P_Freq * 1 );		// wait 50

// 2450  Sensors: no change  IMEs: no change
motor[ port8 ] = -8;
motor[ port9 ] = -8;
motor[ port10 ] = -8;
wait1Msec( P_Freq * 2 );		// wait 100

// 2550  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 3 );		// wait 150

// 2700  Sensors: no change  IMEs: no change
motor[ port8 ] = -11;
motor[ port9 ] = -11;
motor[ port10 ] = -11;
wait1Msec( P_Freq * 1 );		// wait 50

// 2750  Sensors: no change  IMEs: no change
motor[ port8 ] = -50;
motor[ port9 ] = -50;
motor[ port10 ] = -50;
wait1Msec( P_Freq * 2 );		// wait 100

// 2850  Sensors: no change  IMEs: no change
motor[ port8 ] = -57;
motor[ port9 ] = -57;
motor[ port10 ] = -57;
wait1Msec( P_Freq * 15 );		// wait 750

// 3600  Sensors: no change  IMEs: no change
motor[ port8 ] = -27;
motor[ port9 ] = -27;
motor[ port10 ] = -27;
wait1Msec( P_Freq * 1 );		// wait 50

// 3650  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 4 );		// wait 200

// 3850  Sensors: no change  IMEs: no change
motor[ port1 ] = 25;
motor[ port2 ] = 25;
motor[ port3 ] = 25;
motor[ port8 ] = 28;
motor[ port9 ] = 28;
motor[ port10 ] = 28;
wait1Msec( P_Freq * 1 );		// wait 50

// 3900  Sensors: no change  IMEs: no change
motor[ port1 ] = 31;
motor[ port2 ] = 31;
motor[ port3 ] = 31;
motor[ port8 ] = 37;
motor[ port9 ] = 37;
motor[ port10 ] = 37;
wait1Msec( P_Freq * 1 );		// wait 50

// 3950  Sensors: in 1 = 861  IMEs: no change
motor[ port1 ] = 99;
motor[ port2 ] = 99;
motor[ port3 ] = 99;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 2 );		// wait 100

// 4050  Sensors: in 1 = 865  IMEs: no change
motor[ port1 ] = 120;
motor[ port2 ] = 120;
motor[ port3 ] = 120;
wait1Msec( P_Freq * 1 );		// wait 50

// 4100  Sensors: no change  IMEs: no change
motor[ port8 ] = 121;
motor[ port9 ] = 121;
motor[ port10 ] = 121;
wait1Msec( P_Freq * 1 );		// wait 50

// 4150  Sensors: no change  IMEs: no change
motor[ port8 ] = -18;
motor[ port9 ] = -18;
motor[ port10 ] = -18;
wait1Msec( P_Freq * 1 );		// wait 50

// 4200  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 2 );		// wait 100

// 4300  Sensors: no change  IMEs: no change
motor[ port1 ] = -9;
motor[ port2 ] = -9;
motor[ port3 ] = -9;
wait1Msec( P_Freq * 1 );		// wait 50

// 4350  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 6 );		// wait 300

// 4650  Sensors: no change  IMEs: no change
motor[ port8 ] = 11;
motor[ port9 ] = 11;
motor[ port10 ] = 11;
wait1Msec( P_Freq * 1 );		// wait 50

// 4700  Sensors: no change  IMEs: no change
motor[ port8 ] = 16;
motor[ port9 ] = 16;
motor[ port10 ] = 16;
wait1Msec( P_Freq * 1 );		// wait 50

// 4750  Sensors: no change  IMEs: no change
motor[ port8 ] = 24;
motor[ port9 ] = 24;
motor[ port10 ] = 24;
wait1Msec( P_Freq * 1 );		// wait 50

// 4800  Sensors: no change  IMEs: no change
motor[ port1 ] = 7;
motor[ port2 ] = 7;
motor[ port3 ] = 7;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 50

// 4850  Sensors: no change  IMEs: no change
motor[ port1 ] = 62;
motor[ port2 ] = 62;
motor[ port3 ] = 62;
motor[ port8 ] = 41;
motor[ port9 ] = 41;
motor[ port10 ] = 41;
wait1Msec( P_Freq * 1 );		// wait 50

// 4900  Sensors: no change  IMEs: no change
motor[ port1 ] = 77;
motor[ port2 ] = 77;
motor[ port3 ] = 77;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 1 );		// wait 50

// 4950  Sensors: in 1 = 862  IMEs: no change
motor[ port1 ] = 69;
motor[ port2 ] = 69;
motor[ port3 ] = 69;
motor[ port8 ] = -14;
motor[ port9 ] = -14;
motor[ port10 ] = -14;
wait1Msec( P_Freq * 1 );		// wait 50

// 5000  Sensors: in 1 = 866  IMEs: no change
motor[ port1 ] = 6;
motor[ port2 ] = 6;
motor[ port3 ] = 6;
motor[ port8 ] = -4;
motor[ port9 ] = -4;
motor[ port10 ] = -4;
wait1Msec( P_Freq * 2 );		// wait 100

// 5100  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 50

// 5150  Sensors: no change  IMEs: no change
motor[ port1 ] = -41;
motor[ port2 ] = -41;
motor[ port3 ] = -41;
wait1Msec( P_Freq * 1 );		// wait 50

// 5200  Sensors: no change  IMEs: no change
motor[ port1 ] = -56;
motor[ port2 ] = -56;
motor[ port3 ] = -56;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 2 );		// wait 100

// 5300  Sensors: no change  IMEs: no change
motor[ port1 ] = 6;
motor[ port2 ] = 6;
motor[ port3 ] = 6;
motor[ port8 ] = 12;
motor[ port9 ] = 12;
motor[ port10 ] = 12;
wait1Msec( P_Freq * 1 );		// wait 50

// 5350  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 2 );		// wait 100

// 5450  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 2 );		// wait 100

// 5550  Sensors: no change  IMEs: no change
motor[ port8 ] = -11;
motor[ port9 ] = -11;
motor[ port10 ] = -11;
wait1Msec( P_Freq * 1 );		// wait 50

// 5600  Sensors: no change  IMEs: no change
motor[ port8 ] = -18;
motor[ port9 ] = -18;
motor[ port10 ] = -18;
wait1Msec( P_Freq * 1 );		// wait 50

// 5650  Sensors: no change  IMEs: no change
motor[ port8 ] = -41;
motor[ port9 ] = -41;
motor[ port10 ] = -41;
wait1Msec( P_Freq * 2 );		// wait 100

// 5750  Sensors: no change  IMEs: no change
motor[ port1 ] = -33;
motor[ port2 ] = -33;
motor[ port3 ] = -33;
wait1Msec( P_Freq * 2 );		// wait 100

// 5850  Sensors: no change  IMEs: no change
motor[ port1 ] = -23;
motor[ port2 ] = -23;
motor[ port3 ] = -23;
motor[ port8 ] = -53;
motor[ port9 ] = -53;
motor[ port10 ] = -53;
wait1Msec( P_Freq * 2 );		// wait 100

// 5950  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = -4;
motor[ port9 ] = -4;
motor[ port10 ] = -4;
wait1Msec( P_Freq * 1 );		// wait 50

// 6000  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 50

// 6050  Sensors: no change  IMEs: no change
motor[ port8 ] = -4;
motor[ port9 ] = -4;
motor[ port10 ] = -4;
wait1Msec( P_Freq * 6 );		// wait 300

// 6350  Sensors: no change  IMEs: no change
motor[ port1 ] = -52;
motor[ port2 ] = -52;
motor[ port3 ] = -52;
wait1Msec( P_Freq * 2 );		// wait 100

// 6450  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 21 );		// wait 1050

// 7500  Sensors: no change  IMEs: no change
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 5 );		// wait 250

// 7750  Sensors: in 1 = 863  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 27 );		// wait 1350

// 9100  Sensors: in 1 = 866  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 13 );		// wait 650

// 9750  Sensors: in 1 = 861  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 3 );		// wait 150

// 9900  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 12 );		// wait 600

// 10500  Sensors: no change  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 2 );		// wait 100

// 10600  Sensors: no change  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;
wait1Msec( P_Freq * 20 );		// wait 1000

// 11600  Sensors: no change  IMEs: no change
motor[ port5 ] = 127;
motor[ port6 ] = 127;
wait1Msec( P_Freq * 21 );		// wait 1050

// 12650  Sensors: in 1 = 524  in 2 = 2209  IMEs: no change
motor[ port1 ] = 127;
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
motor[ port10 ] = 127;
wait1Msec( P_Freq * 2 );		// wait 100

// 12750  Sensors: in 1 = 717  in 2 = 2206  IMEs: no change
motor[ port5 ] = 0;
motor[ port6 ] = 0;
wait1Msec( P_Freq * 7 );		// wait 350

// 13100  Sensors: in 1 = 769  in 2 = 2341  IMEs: no change
motor[ port1 ] = 0;
motor[ port2 ] = 0;
motor[ port3 ] = 0;
motor[ port8 ] = 0;
motor[ port9 ] = 0;
motor[ port10 ] = 0;

// Sensor(s) detected, nice!
// Integeated Encoder Module(s) detected, sweet!
// Begin recording in:  3 . . . . 2 . . . . 1 . . . .
// BEGIN AUTONOMOUS RECORDING
/*<<<<---- START COPY ----------------------------------------------------------------------*/
wait1Msec( P_Freq * 4 );		// wait 200

// 200  Sensors: no change  IMEs: no change
motor[ port1 ] = -6;
motor[ port2 ] = -6;
motor[ port3 ] = -6;
motor[ port8 ] = 9;
motor[ port9 ] = 9;
motor[ port10 ] = 9;
wait1Msec( P_Freq * 2 );		// wait 100

// 300  Sensors: no change  IMEs: no change
motor[ port8 ] = 18;
motor[ port9 ] = 18;
motor[ port10 ] = 18;
wait1Msec( P_Freq * 1 );		// wait 50

// 350  Sensors: no change  IMEs: no change
motor[ port1 ] = -10;
motor[ port2 ] = -10;
motor[ port3 ] = -10;
motor[ port8 ] = 26;
motor[ port9 ] = 26;
motor[ port10 ] = 26;
wait1Msec( P_Freq * 2 );		// wait 100

// 450  Sensors: no change  IMEs: no change
motor[ port1 ] = -13;
motor[ port2 ] = -13;
motor[ port3 ] = -13;
wait1Msec( P_Freq * 3 );		// wait 150

// 600  Sensors: no change  IMEs: no change
motor[ port1 ] = -18;
motor[ port2 ] = -18;
motor[ port3 ] = -18;
motor[ port8 ] = 31;
motor[ port9 ] = 31;
motor[ port10 ] = 31;
wait1Msec( P_Freq * 9 );		// wait 450

// 1050  Sensors: no change  IMEs: no change
motor[ port8 ] = 39;
motor[ port9 ] = 39;
motor[ port10 ] = 39;
wait1Msec( P_Freq * 2 );		// wait 100

// 1150  Sensors: no change  IMEs: no change
motor[ port8 ] = 51;
motor[ port9 ] = 51;
motor[ port10 ] = 51;
wait1Msec( P_Freq * 1 );		// wait 50

// 1200  Sensors: no change  IMEs: no change
motor[ port8 ] = 57;
motor[ port9 ] = 57;
motor[ port10 ] = 57;
wait1Msec( P_Freq * 2 );		// wait 100

// 1300  Sensors: no change  IMEs: no change
motor[ port8 ] = 61;
motor[ port9 ] = 61;
motor[ port10 ] = 61;
wait1Msec( P_Freq * 2 );		// wait 100

// 1400  Sensors: no change  IMEs: no change
motor[ port8 ] = 66;
motor[ port9 ] = 66;
motor[ port10 ] = 66;
wait1Msec( P_Freq * 1 );		// wait 50

// 1450  Sensors: no change  IMEs: no change
motor[ port8 ] = 75;
motor[ port9 ] = 75;
motor[ port10 ] = 75;
wait1Msec( P_Freq * 1 );		// wait 50

// 1500  Sensors: no change  IMEs: no change
motor[ port1 ] = -22;
motor[ port2 ] = -22;
motor[ port3 ] = -22;
motor[ port8 ] = 78;
motor[ port9 ] = 78;
motor[ port10 ] = 78;
wait1Msec( P_Freq * 1 );		// wait 50

// 1550  Sensors: no change  IMEs: no change
motor[ port8 ] = 88;
motor[ port9 ] = 88;
motor[ port10 ] = 88;
wait1Msec( P_Freq * 1 );		// wait 50

// 1600  Sensors: no change  IMEs: no change
motor[ port8 ] = 94;
motor[ port9 ] = 94;
motor[ port10 ] = 94;
wait1Msec( P_Freq * 3 );		// wait 150

// 1750  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 100;
motor[ port9 ] = 100;
motor[ port10 ] = 100;
wait1Msec( P_Freq * 2 );		// wait 100

// 1850  Sensors: no change  IMEs: no change
motor[ port8 ] = 27;
motor[ port9 ] = 27;
motor[ port10 ] = 27;
wait1Msec( P_Freq * 2 );		// wait 100

// 1950  Sensors: no change  IMEs: no change
motor[ port1 ] = -49;
motor[ port2 ] = -49;
motor[ port3 ] = -49;
motor[ port8 ] = -45;
motor[ port9 ] = -45;
motor[ port10 ] = -45;
wait1Msec( P_Freq * 1 );		// wait 50

// 2000  Sensors: no change  IMEs: no change
motor[ port1 ] = -70;
motor[ port2 ] = -70;
motor[ port3 ] = -70;
motor[ port8 ] = -74;
motor[ port9 ] = -74;
motor[ port10 ] = -74;
wait1Msec( P_Freq * 1 );		// wait 50

// 2050  Sensors: no change  IMEs: no change
motor[ port1 ] = -82;
motor[ port2 ] = -82;
motor[ port3 ] = -82;
motor[ port8 ] = -96;
motor[ port9 ] = -96;
motor[ port10 ] = -96;
wait1Msec( P_Freq * 1 );		// wait 50

// 2100  Sensors: no change  IMEs: no change
motor[ port8 ] = -90;
motor[ port9 ] = -90;
motor[ port10 ] = -90;
wait1Msec( P_Freq * 4 );		// wait 200

// 2300  Sensors: no change  IMEs: no change
motor[ port8 ] = -85;
motor[ port9 ] = -85;
motor[ port10 ] = -85;
wait1Msec( P_Freq * 1 );		// wait 50

// 2350  Sensors: no change  IMEs: no change
motor[ port1 ] = -41;
motor[ port2 ] = -41;
motor[ port3 ] = -41;
motor[ port8 ] = 39;
motor[ port9 ] = 39;
motor[ port10 ] = 39;
wait1Msec( P_Freq * 2 );		// wait 100

// 2450  Sensors: no change  IMEs: no change
motor[ port1 ] = -34;
motor[ port2 ] = -34;
motor[ port3 ] = -34;
motor[ port8 ] = 72;
motor[ port9 ] = 72;
motor[ port10 ] = 72;
wait1Msec( P_Freq * 1 );		// wait 50

// 2500  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 50

// 2550  Sensors: no change  IMEs: no change
motor[ port8 ] = 69;
motor[ port9 ] = 69;
motor[ port10 ] = 69;
wait1Msec( P_Freq * 1 );		// wait 50

// 2600  Sensors: no change  IMEs: no change
motor[ port1 ] = -16;
motor[ port2 ] = -16;
motor[ port3 ] = -16;
wait1Msec( P_Freq * 1 );		// wait 50

// 2650  Sensors: no change  IMEs: no change
motor[ port1 ] = -67;
motor[ port2 ] = -67;
motor[ port3 ] = -67;
motor[ port8 ] = 63;
motor[ port9 ] = 63;
motor[ port10 ] = 63;
wait1Msec( P_Freq * 1 );		// wait 50

// 2700  Sensors: no change  IMEs: no change
motor[ port8 ] = 57;
motor[ port9 ] = 57;
motor[ port10 ] = 57;
wait1Msec( P_Freq * 1 );		// wait 50

// 2750  Sensors: no change  IMEs: no change
motor[ port1 ] = -9;
motor[ port2 ] = -9;
motor[ port3 ] = -9;
wait1Msec( P_Freq * 1 );		// wait 50

// 2800  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 49;
motor[ port9 ] = 49;
motor[ port10 ] = 49;
wait1Msec( P_Freq * 1 );		// wait 50

// 2850  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 4 );		// wait 200

// 3050  Sensors: no change  IMEs: no change
motor[ port1 ] = -5;
motor[ port2 ] = -5;
motor[ port3 ] = -5;
wait1Msec( P_Freq * 1 );		// wait 50

// 3100  Sensors: no change  IMEs: no change
motor[ port1 ] = -26;
motor[ port2 ] = -26;
motor[ port3 ] = -26;
wait1Msec( P_Freq * 2 );		// wait 100

// 3200  Sensors: no change  IMEs: no change
motor[ port1 ] = -29;
motor[ port2 ] = -29;
wait1Msec( P_Freq * 2 );		// wait 100

// 3300  Sensors: no change  IMEs: no change
motor[ port1 ] = -33;
motor[ port2 ] = -33;
motor[ port3 ] = -33;
wait1Msec( P_Freq * 20 );		// wait 1000

// 4300  Sensors: no change  IMEs: no change
motor[ port8 ] = -10;
motor[ port9 ] = -10;
motor[ port10 ] = -10;
wait1Msec( P_Freq * 1 );		// wait 50

// 4350  Sensors: no change  IMEs: no change
motor[ port1 ] = -29;
motor[ port2 ] = -29;
motor[ port3 ] = -29;
motor[ port8 ] = -18;
motor[ port9 ] = -18;
motor[ port10 ] = -18;
wait1Msec( P_Freq * 1 );		// wait 50

// 4400  Sensors: no change  IMEs: no change
motor[ port1 ] = -19;
motor[ port2 ] = -19;
motor[ port3 ] = -19;
motor[ port8 ] = -32;
motor[ port9 ] = -32;
motor[ port10 ] = -32;
wait1Msec( P_Freq * 12 );		// wait 600

// 5000  Sensors: no change  IMEs: no change
motor[ port8 ] = -37;
motor[ port9 ] = -37;
motor[ port10 ] = -37;
wait1Msec( P_Freq * 7 );		// wait 350

// 5350  Sensors: no change  IMEs: no change
motor[ port1 ] = -22;
motor[ port2 ] = -22;
motor[ port3 ] = -22;
wait1Msec( P_Freq * 2 );		// wait 100

// 5450  Sensors: no change  IMEs: no change
motor[ port1 ] = -43;
motor[ port2 ] = -43;
motor[ port3 ] = -43;
wait1Msec( P_Freq * 1 );		// wait 50

// 5500  Sensors: no change  IMEs: no change
motor[ port1 ] = -50;
motor[ port2 ] = -50;
motor[ port3 ] = -50;
motor[ port8 ] = -18;
motor[ port9 ] = -18;
motor[ port10 ] = -18;
wait1Msec( P_Freq * 1 );		// wait 50

// 5550  Sensors: no change  IMEs: no change
motor[ port1 ] = -57;
motor[ port2 ] = -57;
motor[ port3 ] = -57;
motor[ port8 ] = -11;
motor[ port9 ] = -11;
motor[ port10 ] = -11;
wait1Msec( P_Freq * 2 );		// wait 100

// 5650  Sensors: no change  IMEs: no change
motor[ port1 ] = -48;
motor[ port2 ] = -48;
motor[ port3 ] = -48;
wait1Msec( P_Freq * 1 );		// wait 50

// 5700  Sensors: no change  IMEs: no change
motor[ port1 ] = -41;
motor[ port2 ] = -41;
motor[ port3 ] = -41;
wait1Msec( P_Freq * 1 );		// wait 50

// 5750  Sensors: no change  IMEs: no change
motor[ port1 ] = -33;
motor[ port2 ] = -33;
motor[ port3 ] = -33;
wait1Msec( P_Freq * 3 );		// wait 150

// 5900  Sensors: no change  IMEs: no change
motor[ port1 ] = -29;
motor[ port2 ] = -29;
motor[ port3 ] = -29;
motor[ port8 ] = -8;
motor[ port9 ] = -8;
motor[ port10 ] = -8;
wait1Msec( P_Freq * 1 );		// wait 50

// 5950  Sensors: no change  IMEs: no change
motor[ port1 ] = -23;
motor[ port2 ] = -23;
wait1Msec( P_Freq * 1 );		// wait 50

// 6000  Sensors: no change  IMEs: no change
motor[ port1 ] = -40;
motor[ port2 ] = -40;
motor[ port3 ] = -40;
motor[ port8 ] = -27;
motor[ port9 ] = -27;
motor[ port10 ] = -27;
wait1Msec( P_Freq * 1 );		// wait 50

// 6050  Sensors: in 1 = 864  IMEs: no change
motor[ port1 ] = -73;
motor[ port2 ] = -73;
motor[ port3 ] = -73;
motor[ port8 ] = -81;
motor[ port9 ] = -81;
motor[ port10 ] = -81;
wait1Msec( P_Freq * 2 );		// wait 100

// 6150  Sensors: no change  IMEs: no change
motor[ port1 ] = -113;
motor[ port2 ] = -113;
motor[ port3 ] = -113;
motor[ port8 ] = -101;
motor[ port9 ] = -101;
motor[ port10 ] = -101;
wait1Msec( P_Freq * 1 );		// wait 50

// 6200  Sensors: no change  IMEs: no change
motor[ port1 ] = -123;
motor[ port2 ] = -123;
motor[ port3 ] = -123;
motor[ port8 ] = -105;
motor[ port9 ] = -105;
motor[ port10 ] = -105;
wait1Msec( P_Freq * 1 );		// wait 50

// 6250  Sensors: no change  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -111;
motor[ port9 ] = -111;
motor[ port10 ] = -111;
wait1Msec( P_Freq * 5 );		// wait 250

// 6500  Sensors: in 1 = 867  IMEs: no change
motor[ port8 ] = -97;
motor[ port9 ] = -97;
motor[ port10 ] = -97;
wait1Msec( P_Freq * 1 );		// wait 50

// 6550  Sensors: no change  IMEs: no change
motor[ port1 ] = -121;
motor[ port2 ] = -121;
motor[ port3 ] = -121;
motor[ port8 ] = -89;
motor[ port9 ] = -89;
motor[ port10 ] = -89;
wait1Msec( P_Freq * 1 );		// wait 50

// 6600  Sensors: no change  IMEs: no change
motor[ port1 ] = -114;
motor[ port2 ] = -114;
motor[ port3 ] = -114;
wait1Msec( P_Freq * 2 );		// wait 100

// 6700  Sensors: in 1 = 863  IMEs: no change
motor[ port1 ] = -87;
motor[ port2 ] = -87;
motor[ port3 ] = -87;
wait1Msec( P_Freq * 2 );		// wait 100

// 6800  Sensors: no change  IMEs: no change
motor[ port1 ] = -92;
motor[ port2 ] = -92;
motor[ port3 ] = -92;
wait1Msec( P_Freq * 1 );		// wait 50

// 6850  Sensors: no change  IMEs: no change
motor[ port1 ] = -84;
motor[ port2 ] = -84;
motor[ port3 ] = -84;
motor[ port8 ] = -82;
motor[ port9 ] = -82;
motor[ port10 ] = -82;
wait1Msec( P_Freq * 2 );		// wait 100

// 6950  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = -8;
motor[ port9 ] = -8;
motor[ port10 ] = -8;
wait1Msec( P_Freq * 2 );		// wait 100

// 7050  Sensors: in 1 = 865  IMEs: no change
motor[ port8 ] = -4;
motor[ port9 ] = -4;
motor[ port10 ] = -4;
wait1Msec( P_Freq * 2 );		// wait 100

// 7150  Sensors: no change  IMEs: no change
motor[ port1 ] = -13;
motor[ port2 ] = -13;
motor[ port3 ] = -13;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 50

// 7200  Sensors: no change  IMEs: no change
motor[ port1 ] = -19;
motor[ port2 ] = -19;
motor[ port3 ] = -19;
motor[ port8 ] = 29;
motor[ port9 ] = 29;
motor[ port10 ] = 29;
wait1Msec( P_Freq * 2 );		// wait 100

// 7300  Sensors: no change  IMEs: no change
motor[ port1 ] = -12;
motor[ port2 ] = -12;
motor[ port3 ] = -12;
wait1Msec( P_Freq * 1 );		// wait 50

// 7350  Sensors: no change  IMEs: no change
motor[ port1 ] = -8;
motor[ port2 ] = -8;
motor[ port3 ] = -8;
motor[ port8 ] = 17;
motor[ port9 ] = 17;
motor[ port10 ] = 17;
wait1Msec( P_Freq * 1 );		// wait 50

// 7400  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 5 );		// wait 250

// 7650  Sensors: no change  IMEs: no change
motor[ port8 ] = 26;
motor[ port9 ] = 26;
motor[ port10 ] = 26;
wait1Msec( P_Freq * 1 );		// wait 50

// 7700  Sensors: no change  IMEs: no change
motor[ port1 ] = -7;
motor[ port2 ] = -7;
motor[ port3 ] = -7;
wait1Msec( P_Freq * 1 );		// wait 50

// 7750  Sensors: no change  IMEs: no change
motor[ port1 ] = -16;
motor[ port2 ] = -16;
motor[ port3 ] = -16;
motor[ port8 ] = 31;
motor[ port9 ] = 31;
motor[ port10 ] = 31;
wait1Msec( P_Freq * 2 );		// wait 100

// 7850  Sensors: no change  IMEs: no change
motor[ port1 ] = -19;
motor[ port2 ] = -19;
motor[ port3 ] = -19;
wait1Msec( P_Freq * 2 );		// wait 100

// 7950  Sensors: no change  IMEs: no change
motor[ port8 ] = 36;
motor[ port9 ] = 36;
motor[ port10 ] = 36;
wait1Msec( P_Freq * 7 );		// wait 350

// 8300  Sensors: no change  IMEs: no change
motor[ port1 ] = -25;
motor[ port2 ] = -25;
motor[ port3 ] = -25;
wait1Msec( P_Freq * 8 );		// wait 400

// 8700  Sensors: no change  IMEs: no change
motor[ port8 ] = 32;
motor[ port9 ] = 32;
motor[ port10 ] = 32;
wait1Msec( P_Freq * 1 );		// wait 50

// 8750  Sensors: no change  IMEs: no change
motor[ port8 ] = 26;
motor[ port9 ] = 26;
motor[ port10 ] = 26;
wait1Msec( P_Freq * 2 );		// wait 100

// 8850  Sensors: no change  IMEs: no change
motor[ port8 ] = 22;
motor[ port9 ] = 22;
motor[ port10 ] = 22;
wait1Msec( P_Freq * 4 );		// wait 200

// 9050  Sensors: no change  IMEs: no change
motor[ port8 ] = 19;
motor[ port9 ] = 19;
motor[ port10 ] = 19;
wait1Msec( P_Freq * 2 );		// wait 100

// 9150  Sensors: no change  IMEs: no change
motor[ port8 ] = 8;
motor[ port9 ] = 8;
motor[ port10 ] = 8;
wait1Msec( P_Freq * 1 );		// wait 50

// 9200  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 5 );		// wait 250

// 9450  Sensors: no change  IMEs: no change
motor[ port1 ] = -33;
motor[ port2 ] = -33;
motor[ port3 ] = -33;
motor[ port8 ] = -46;
motor[ port9 ] = -46;
motor[ port10 ] = -46;
wait1Msec( P_Freq * 1 );		// wait 50

// 9500  Sensors: no change  IMEs: no change
motor[ port1 ] = -55;
motor[ port2 ] = -55;
motor[ port3 ] = -55;
motor[ port8 ] = -79;
motor[ port9 ] = -79;
motor[ port10 ] = -79;
wait1Msec( P_Freq * 1 );		// wait 50

// 9550  Sensors: no change  IMEs: no change
motor[ port1 ] = -65;
motor[ port2 ] = -65;
motor[ port3 ] = -65;
motor[ port8 ] = -97;
motor[ port9 ] = -97;
motor[ port10 ] = -97;
wait1Msec( P_Freq * 1 );		// wait 50

// 9600  Sensors: no change  IMEs: no change
motor[ port1 ] = -69;
motor[ port2 ] = -69;
motor[ port3 ] = -69;
wait1Msec( P_Freq * 1 );		// wait 50

// 9650  Sensors: no change  IMEs: no change
motor[ port1 ] = -77;
motor[ port2 ] = -77;
motor[ port3 ] = -77;
wait1Msec( P_Freq * 1 );		// wait 50

// 9700  Sensors: no change  IMEs: no change
motor[ port1 ] = -92;
motor[ port2 ] = -92;
motor[ port3 ] = -92;
wait1Msec( P_Freq * 1 );		// wait 50

// 9750  Sensors: no change  IMEs: no change
motor[ port1 ] = -108;
motor[ port2 ] = -108;
motor[ port3 ] = -108;
wait1Msec( P_Freq * 1 );		// wait 50

// 9800  Sensors: in 1 = 862  IMEs: no change
motor[ port1 ] = -115;
motor[ port2 ] = -115;
motor[ port3 ] = -115;
wait1Msec( P_Freq * 1 );		// wait 50

// 9850  Sensors: no change  IMEs: no change
motor[ port1 ] = -127;
motor[ port2 ] = -127;
motor[ port3 ] = -127;
wait1Msec( P_Freq * 6 );		// wait 300

// 10150  Sensors: no change  IMEs: no change
motor[ port8 ] = -110;
motor[ port9 ] = -110;
motor[ port10 ] = -110;
wait1Msec( P_Freq * 5 );		// wait 250

// 10400  Sensors: no change  IMEs: no change
motor[ port8 ] = -114;
motor[ port9 ] = -114;
motor[ port10 ] = -114;
wait1Msec( P_Freq * 1 );		// wait 50

// 10450  Sensors: no change  IMEs: no change
motor[ port8 ] = -118;
motor[ port9 ] = -118;
motor[ port10 ] = -118;
wait1Msec( P_Freq * 3 );		// wait 150

// 10600  Sensors: no change  IMEs: no change
motor[ port8 ] = -127;
motor[ port9 ] = -127;
motor[ port10 ] = -127;
wait1Msec( P_Freq * 5 );		// wait 250

// 10850  Sensors: no change  IMEs: no change
motor[ port8 ] = -118;
motor[ port9 ] = -118;
motor[ port10 ] = -118;
wait1Msec( P_Freq * 2 );		// wait 100

// 10950  Sensors: in 2 = 2333  IMEs: no change
motor[ port1 ] = 43;
motor[ port2 ] = 43;
motor[ port3 ] = 43;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
motor[ port10 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 50

// 11000  Sensors: no change  IMEs: no change
motor[ port1 ] = 1;
motor[ port2 ] = 1;
motor[ port3 ] = 1;


}
