#pragma config(Sensor, in3,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    pot2,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftencoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           ballarm,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightfront,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightmiddle,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           rightback,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           catapult1,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           catapult2,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftfront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftmiddle,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftback,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//catapult
int Initial_Value = 50;
int Final_Value = 650;
int Error_Margin = 75;
//ballarm
int Initial_Ballarm = 2020;
int Final_Ballarm = 40;
int Error_Ballarm = 73;

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
task LCD(){
	bLCDBacklight = true;
	string mainBattery, backupBattery;

	while(true)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);

		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		displayNextLCDString(backupBattery);

		wait1Msec(100);
	}
}
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	startTask(LCD);
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//catapult
void Catapult_launch(){
	while(SensorValue[pot] >= Initial_Value){
		motor[catapult1]=127;
		motor[catapult2]=127;
	}
	while(SensorValue[pot] <= Final_Value - Error_Margin){
		motor[catapult1]=127;
		motor[catapult2]=127;
	}
	motor[catapult1] = 50;
	motor[catapult2] = 50;
	wait1Msec(5);

	motor[catapult1] = 0;
	motor[catapult2] = 0;
}

//ballarm
void allarm(){
	while(SensorValue[pot2] >= Initial_Ballarm){
		motor[ballarm]=127;
	}
	while(SensorValue[pot2] <= Final_Ballarm - Error_Ballarm){
		motor[ballarm]=-127;
	}
	motor[ballarm] = -50;
	wait1Msec(5);

	motor[ballarm] = 0;
}

void moveUntilDistance(int distanceInDegrees)
{

	SensorValue(rightencoder) = 0;
	SensorValue(leftencoder) = 0;
	wait1Msec(100);

	while(SensorValue[rightencoder] < distanceInDegrees)
	{
		motor[rightback] = 100;
		motor[rightfront] = 100;
		motor[rightmiddle] = 100;
		motor[leftback] = 100;
		motor[leftfront] = 100;
		motor[leftmiddle] = 100;
	}
	motor[rightback] = 0;
	motor[rightfront] = 0;
	motor[rightmiddle] = 0;
	motor[leftback] = 0;
	motor[leftfront] = 0;
	motor[leftmiddle] = 0;
	wait1Msec(100);
}

void pointTurnRight(int turnDistanceRight)
{

	SensorValue(rightencoder) = 0;
	SensorValue(leftencoder) = 0;
	wait1Msec(100);

	while(-SensorValue[leftencoder] < turnDistanceRight)
	{
		motor[rightback] = -100;
		motor[rightfront] = -100;
		motor[rightmiddle] = -100;
		motor[leftback] = 100;
		motor[leftfront] = 100;
		motor[leftmiddle] = 100;
	}
	motor[rightback] = 0;
	motor[rightfront] = 0;
	motor[rightmiddle] = 0;
	motor[leftback] = 0;
	motor[leftfront] = 0;
	motor[leftmiddle] = 0;
	wait1Msec(100);
}

void pointTurnLeft(int turnDistanceLeft)
{

	SensorValue(rightencoder) = 0;
	SensorValue(leftencoder) = 0;
	wait1Msec(100);

	while(SensorValue[rightencoder] < turnDistanceLeft)
	{
		motor[rightback] = 100;
		motor[rightfront] = 100;
		motor[rightmiddle] = 100;
		motor[leftback] = -100;
		motor[leftfront] = -100;
		motor[leftmiddle] = -100;
	}
	motor[rightback] = 0;
	motor[rightfront] = 0;
	motor[rightmiddle] = 0;
	motor[leftback] = 0;
	motor[leftfront] = 0;
	motor[leftmiddle] = 0;
	wait1Msec(100);
}

task autonomous()
{

	moveUntilDistance(1333); //bot moves to the cap

	motor[intake]= 127;  //intakes ball from cap

	moveUntilDistance(-100); //travels backwards

	wait1Msec(500);// enough time for intake to intake the ball

	pointTurnRight(300); //turns- so that the bot can go to final cap

	motor[intake]= 0; //intake stops running
	wait1Msec(100);
	//moveUntilDistance(-200); //travels backwards

	//pointTurnLeft(30); //turns to face final cap

	//moveUntilDistance(70); //travels forward to cap

	//motor[intake]= 127;  //flips cap
	//wait1Msec(500);

	//pointTurnLeft(65); //turns to face platform

	//moveUntilDistance(100) //levels on field

	//moveUntilDistance(-500); //travels to platform


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//catapult
task Catapult(){
	while(true){
		if (vexRT(Btn5UXmtr2)==1){
			while(SensorValue[pot] >= Initial_Value){
				motor[catapult1]=127;
				motor[catapult2]=127;
			}
			while(SensorValue[pot] <= Final_Value - Error_Margin){
				motor[catapult1]=127;
				motor[catapult2]=127;
			}
			motor[catapult1] = -50;
			motor[catapult2] = -50;
			wait1Msec(5);
			motor[catapult1] = 0;
			motor[catapult2] = 0;
		}
		else if (vexRT(Btn5DXmtr2)==1){
			motor[catapult1]=127;
			motor[catapult2]=127;
		}
		else{
			motor[catapult1] = 0;
			motor[catapult2] = 0;
		}
	}
}

//ballarm
task allarm(){
	while(true){
		if (vexRT(Btn8U)==1){ //Btn5UXmtr2
			while(SensorValue[pot2] >= Initial_Ballarm){
				motor[ballarm]=127;
			}
			while(SensorValue[pot2] <= Final_Ballarm - Error_Ballarm){
				motor[ballarm]=-127;
			}
			motor[ballarm] = -50;
			wait1Msec(5);

			motor[ballarm] = 0;
		}
		else if (vexRT(Btn8D)==1){//Btn5DXmtr2
			motor[ballarm]=-127;
		}
		else{
			motor[ballarm]=0;
		}
	}
}

task usercontrol()
{
	startTask (Catapult);
	startTask (allarm);
	while(true)
	{

		motor[rightfront] = vexRT[Ch2];
		motor[rightmiddle]  = vexRT[Ch2];
		motor[leftfront] = vexRT[Ch3];
		motor[leftmiddle]  = vexRT[Ch3];
		motor[rightback]= vexRT[Ch2];
		motor[leftback]= vexRT[Ch3];

		if(vexRT[Btn6U] == 1)
		{
			motor[intake] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[intake] = 127;
		}
		else
		{
			motor[intake] = 0;
		}

	}}
