#pragma config(Sensor, in1,    Pot,            sensorPotentiometer)
#pragma config(Motor,  port1,           chasis_L3,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           chasis_L2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           chasis_L1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Intake,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Catapult_1,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Catapult_2,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           chasis_R1,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           chasis_R2,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          chasis_R3,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Catapult(){
	while(true){
		if (vexRT[Btn5UXmtr2] == 1){
			motor[Catapult_1]=127;
			motor[Catapult_2]=127;
		}
		else if (vexRT[Btn5DXmtr2]==1){
			while (SensorValue[Pot]>50){
				motor[Catapult_1]=127;
			motor[Catapult_2]=127;
			}
			while(SensorValue[Pot]<700){
			motor[Catapult_1]=127;
			motor[Catapult_2]=127;
			}
			motor[Catapult_1]=-5;
			motor[Catapult_2]=-5;
			wait1Msec(5);
			motor[Catapult_1]=0;
			motor[Catapult_2]=0;
		}
		else{
			motor[Catapult_1]=0;
			motor[Catapult_2]=0;
		}
	}
}

task main()
{
	startTask (Catapult);
	while(true){
		//chasis
		motor[chasis_R1]= vexRT[Ch2];
		motor[chasis_R2]= vexRT[Ch2];
		motor[chasis_R3]= vexRT[Ch2];
		motor[chasis_L1]= vexRT[Ch3];
		motor[chasis_L2]= vexRT[Ch3];
		motor[chasis_L3]= vexRT[Ch3];

		//ball intake
		if (vexRT[Btn6UXmtr2] == 1){
			motor[Intake]=127;
		}
		else if (vexRT[Btn6DXmtr2] ==1){
			motor[Intake]=-127;
		}
		else{
			motor[Intake]=0;
		}

		//


	}
}
